/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package business;

import org.junit.Test;

import business.Inventory;
import models.Product;

import static org.junit.Assert.*;

public class InventoryTest {
    @Test
    public void testCreateProduct() {
    	Product product = new Product("Vaso", "DC", 1500);
        Inventory inventory = new Inventory();
        assertTrue("createProduct should return 'true'", inventory.createProduct(product));
    }
}
