/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package business;

import models.Product;

public class Inventory {

	public boolean createProduct(Product product) {
		return true;
	}
}
